-- ESX-specific client overrides for this resource.
--
-- lyre_bridge already provides init/autoDetect and the default bridge methods
-- (showNotification, giveVehicleKeys, getFuel, hasItem, …). Add ESX-only
-- overrides below using the bridgeCandidate helper:
--
--     local bridge = LyreBridge.bridgeCandidate("ESX")
--
--     function bridge:revivePlayer(serverId)
--         ExecuteCommand("revive " .. serverId)
--     end
