-- QBCore-specific client overrides for this resource.
--
-- lyre_bridge already provides init/autoDetect and the default bridge methods
-- (showNotification, giveVehicleKeys, getFuel, hasItem, …). Add QBCore-only
-- overrides below using the bridgeCandidate helper:
--
--     local bridge = LyreBridge.bridgeCandidate("QBCORE")
--
--     function bridge:revivePlayer(serverId)
--         TriggerClientEvent("hospital:client:Revive", serverId)
--     end
