-- Qbox-specific client overrides for this resource.
--
-- lyre_bridge already provides init/autoDetect and the default bridge methods
-- (showNotification, giveVehicleKeys, getFuel, hasItem, …). Add Qbox-only
-- overrides below using the bridgeCandidate helper:
--
--     local bridge = LyreBridge.bridgeCandidate("QBOX")
--
--     function bridge:revivePlayer(serverId)
--         exports.qbx_medical:Revive(serverId)
--     end
