INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('hunting_bait', 'Hunting Bait', 1, 0, 1),
('hunting_trap', 'Hunting Trap', 3, 0, 1),
('portable_campfire', 'Portable Campfire', 2, 0, 1),
('binoculars', 'Binoculars', 1, 0, 1),
('hunting_encyclopedia', 'Hunting Encyclopedia', 1, 0, 1),
('raw_venison_very_bad', 'Raw Venison (Very Bad)', 2, 0, 1),
('raw_venison_bad', 'Raw Venison (Bad)', 2, 0, 1),
('raw_venison_good', 'Raw Venison (Good)', 2, 0, 1),
('raw_venison_very_good', 'Raw Venison (Very Good)', 2, 0, 1),
('raw_rabbit_very_bad', 'Raw Rabbit (Very Bad)', 1, 0, 1),
('raw_rabbit_bad', 'Raw Rabbit (Bad)', 1, 0, 1),
('raw_rabbit_good', 'Raw Rabbit (Good)', 1, 0, 1),
('raw_rabbit_very_good', 'Raw Rabbit (Very Good)', 1, 0, 1),
('raw_pork_very_bad', 'Raw Pork (Very Bad)', 2, 0, 1),
('raw_pork_bad', 'Raw Pork (Bad)', 2, 0, 1),
('raw_pork_good', 'Raw Pork (Good)', 2, 0, 1),
('raw_pork_very_good', 'Raw Pork (Very Good)', 2, 0, 1),
('animal_hide_very_bad', 'Animal Hide (Very Bad)', 3, 0, 1),
('animal_hide_bad', 'Animal Hide (Bad)', 3, 0, 1),
('animal_hide_good', 'Animal Hide (Good)', 3, 0, 1),
('animal_hide_very_good', 'Animal Hide (Very Good)', 3, 0, 1),
('animal_bones_very_bad', 'Animal Bones (Very Bad)', 1, 0, 1),
('animal_bones_bad', 'Animal Bones (Bad)', 1, 0, 1),
('animal_bones_good', 'Animal Bones (Good)', 1, 0, 1),
('animal_bones_very_good', 'Animal Bones (Very Good)', 1, 0, 1),
('animal_organs_very_bad', 'Animal Organs (Very Bad)', 1, 0, 1),
('animal_organs_bad', 'Animal Organs (Bad)', 1, 0, 1),
('animal_organs_good', 'Animal Organs (Good)', 1, 0, 1),
('animal_organs_very_good', 'Animal Organs (Very Good)', 1, 0, 1),
('raw_exotic_meat_very_bad', 'Exotic Meat (Very Bad)', 2, 0, 1),
('raw_exotic_meat_bad', 'Exotic Meat (Bad)', 2, 0, 1),
('raw_exotic_meat_good', 'Exotic Meat (Good)', 2, 0, 1),
('raw_exotic_meat_very_good', 'Exotic Meat (Very Good)', 2, 0, 1),
('exotic_hide_very_bad', 'Exotic Hide (Very Bad)', 3, 0, 1),
('exotic_hide_bad', 'Exotic Hide (Bad)', 3, 0, 1),
('exotic_hide_good', 'Exotic Hide (Good)', 3, 0, 1),
('exotic_hide_very_good', 'Exotic Hide (Very Good)', 3, 0, 1),
('cooked_venison', 'Cooked Venison', 1, 0, 1),
('cooked_rabbit', 'Cooked Rabbit', 1, 0, 1),
('cooked_pork', 'Cooked Pork', 1, 0, 1),
('cooked_exotic', 'Cooked Exotic', 1, 0, 1);
