-- ESX-specific server overrides for this resource.
--
-- lyre_bridge already provides init/autoDetect and the default bridge methods
-- (getPlayerFromId, showNotification, registerUsableItem, …). Add ESX-only
-- overrides below using the bridgeCandidate helper:
--
--     local bridge = LyreBridge.bridgeCandidate("ESX")
--
--     function bridge:hasLicense(source, licenseType, cb)
--         -- ...
--     end
