-- Qbox-specific server overrides for this resource.
--
-- lyre_bridge already provides init/autoDetect and the default bridge methods
-- (getPlayerFromId, showNotification, registerUsableItem, …). Add Qbox-only
-- overrides below using the bridgeCandidate helper:
--
--     local bridge = LyreBridge.bridgeCandidate("QBOX")
--
--     function bridge:hasLicense(source, licenseType, cb)
--         -- ...
--     end
