-- Standalone (no framework) server overrides for this resource.
--
-- lyre_bridge already wires the standalone bridge with sensible defaults.
-- Add overrides below using the bridgeCandidate helper:
--
--     local bridge = LyreBridge.bridgeCandidate("STANDALONE")
--
--     function bridge:methodName(...)
--         -- ...
--     end
