if not LyreBridge or not LyreBridge.setupBridge then
    local runtime = LoadResourceFile("lyre_bridge", "imports/shared.lua")
    assert(runtime, "lyre_bridge imports/shared.lua is missing")

    local fn, err = load(runtime, "@lyre_bridge/imports/shared.lua")
    assert(fn, err)
    fn()
end

local Core = LyreBridge

Core.loadImport("imports/client/helpers.lua")
Core.loadImport("imports/client/setup.lua")
Core.loadImport("imports/client/notifications.lua")
Core.loadImport("imports/client/inventory/providers/ox_inventory.lua")
Core.loadImport("imports/client/inventory/providers/esx.lua")
Core.loadImport("imports/client/inventory/providers/qb.lua")
Core.loadImport("imports/client/inventory/providers/qbox.lua")
Core.loadImport("imports/client/inventory.lua")
Core.loadImport("imports/client/target.lua")
Core.loadImport("imports/client/vehicle_keys/providers/vehicles_keys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/fivecode_carkeys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/stasiek_vehiclekeys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/ti_vehicle_keys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/f_real_car_keys_system.lua")
Core.loadImport("imports/client/vehicle_keys/providers/qb_vehiclekeys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/ak47_qb_vehiclekeys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/ak47_vehiclekeys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/mk_vehiclekeys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/mrnewb_vehiclekeys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/qbx_vehiclekeys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/qs_vehiclekeys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/t1ger_keys.lua")
Core.loadImport("imports/client/vehicle_keys/providers/tgiann_hotwire.lua")
Core.loadImport("imports/client/vehicle_keys/providers/wasabi_carlock.lua")
Core.loadImport("imports/client/vehicle_keys/providers/xd_locksystem.lua")
Core.loadImport("imports/client/vehicle_keys/providers/renewed_vehiclekeys.lua")
Core.loadImport("imports/client/vehicle_keys.lua")
Core.loadImport("imports/client/fuel/providers/shared.lua")
Core.loadImport("imports/client/fuel/providers/lyre_fuel.lua")
Core.loadImport("imports/client/fuel/providers/legacy_fuel.lua")
Core.loadImport("imports/client/fuel/providers/esx_sna_fuel.lua")
Core.loadImport("imports/client/fuel/providers/ps_fuel.lua")
Core.loadImport("imports/client/fuel/providers/lj_fuel.lua")
Core.loadImport("imports/client/fuel/providers/ox_fuel.lua")
Core.loadImport("imports/client/fuel/providers/ti_fuel.lua")
Core.loadImport("imports/client/fuel/providers/frfuel.lua")
Core.loadImport("imports/client/fuel/providers/nd_fuel.lua")
Core.loadImport("imports/client/fuel/providers/bigdaddy_fuel.lua")
Core.loadImport("imports/client/fuel/providers/cdn_fuel.lua")
Core.loadImport("imports/client/fuel/providers/lc_fuel.lua")
Core.loadImport("imports/client/fuel/providers/my_fuel.lua")
Core.loadImport("imports/client/fuel/providers/okok_gas_station.lua")
Core.loadImport("imports/client/fuel/providers/qb_fuel.lua")
Core.loadImport("imports/client/fuel/providers/qb_sna_fuel.lua")
Core.loadImport("imports/client/fuel/providers/rcore_fuel.lua")
Core.loadImport("imports/client/fuel/providers/renewed_fuel.lua")
Core.loadImport("imports/client/fuel/providers/x_fuel.lua")
Core.loadImport("imports/client/fuel.lua")
Core.loadImport("imports/client/dispatch/providers/custom.lua")
Core.loadImport("imports/client/dispatch/providers/cd_dispatch.lua")
Core.loadImport("imports/client/dispatch/providers/qs_dispatch.lua")
Core.loadImport("imports/client/dispatch/providers/ps_dispatch.lua")
Core.loadImport("imports/client/dispatch/providers/rcore_dispatch.lua")
Core.loadImport("imports/client/dispatch/providers/core_dispatch.lua")
Core.loadImport("imports/client/dispatch/providers/tk_dispatch.lua")
Core.loadImport("imports/client/dispatch/providers/codem_dispatch.lua")
Core.loadImport("imports/client/dispatch.lua")
Core.loadImport("imports/client/progress.lua")
