if not LyreBridge or not LyreBridge.setupBridge then
    local runtime = LoadResourceFile("lyre_bridge", "imports/shared.lua")
    assert(runtime, "lyre_bridge imports/shared.lua is missing")

    local fn, err = load(runtime, "@lyre_bridge/imports/shared.lua")
    assert(fn, err)
    fn()
end

local Core = LyreBridge

Core.loadImport("imports/server/helpers.lua")
Core.loadImport("imports/server/setup.lua")
Core.loadImport("imports/server/sql.lua")
Core.loadImport("imports/server/framework.lua")
Core.loadImport("imports/server/players.lua")
Core.loadImport("imports/server/inventory/providers/ox_inventory.lua")
Core.loadImport("imports/server/inventory/providers/qs_inventory.lua")
Core.loadImport("imports/server/inventory/providers/esx.lua")
Core.loadImport("imports/server/inventory/providers/qb.lua")
Core.loadImport("imports/server/inventory.lua")
Core.loadImport("imports/server/usable_items/providers/ox_inventory.lua")
Core.loadImport("imports/server/usable_items/providers/qs_inventory.lua")
Core.loadImport("imports/server/usable_items/providers/esx.lua")
Core.loadImport("imports/server/usable_items/providers/qb.lua")
Core.loadImport("imports/server/usable_items/providers/qbox.lua")
Core.loadImport("imports/server/usable_items.lua")
Core.loadImport("imports/server/society/providers/esx.lua")
Core.loadImport("imports/server/society/providers/qb.lua")
Core.loadImport("imports/server/society.lua")
Core.loadImport("imports/server/offline_accounts/providers/esx.lua")
Core.loadImport("imports/server/offline_accounts/providers/qb.lua")
Core.loadImport("imports/server/offline_accounts.lua")
Core.loadImport("imports/server/dispatch/providers/custom.lua")
Core.loadImport("imports/server/dispatch/providers/zero_r_dispatch.lua")
Core.loadImport("imports/server/dispatch/providers/fd_dispatch.lua")
Core.loadImport("imports/server/dispatch/providers/rcore_dispatch.lua")
Core.loadImport("imports/server/dispatch/providers/ps_dispatch.lua")
Core.loadImport("imports/server/dispatch/providers/cd_dispatch.lua")
Core.loadImport("imports/server/dispatch/providers/lb_tablet.lua")
Core.loadImport("imports/server/dispatch.lua")
